---
abstract: 'Helps implement RESTful architecture in CGI applications'
author:
  - 'Jaldhar H. Vyas <jaldhar@braincells.com>'
build_requires:
  Test::WWW::Mechanize::CGIApp: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Plugin-REST
provides:
  CGI::Application::Plugin::REST:
    file: lib/CGI/Application/Plugin/REST.pm
    version: 0.1
requires:
  CGI::Application: 4.04
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
